version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  bootstrap_files = ["assets"]

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "prettier"
enabled = true